CREATE TABLE ARBITRAGE_OPPORTUNITY (
    ID BIGSERIAL PRIMARY KEY,
    SRC_CURRENCY VARCHAR(10) NOT NULL,
    DST_CURRENCY VARCHAR(10) NOT NULL,
    FIND_TIME TIMESTAMP NOT NULL,
    NOBITEX_PRICE NUMERIC NOT NULL,
    WALLEX_PRICE NUMERIC NOT NULL,
    DIFFERENCE NUMERIC NOT NULL,
    DIFFERENCE_PERCENT NUMERIC NOT NULL
);
