CREATE TABLE BOT_CHAT (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    USER_FIRST_NAME VARCHAR(100),
    CHAT_ID BIGINT NOT NULL,
    SUBBED BOOLEAN NOT NULL,
    LAST_SUB_TIME TIMESTAMP NOT NULL,
    LAST_UNSUB_TIME TIMESTAMP
);
